// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbPguKOd1ahIWG-KoxusLqJ1hTJKGsxOc',
    appId: '1:628420378856:web:af8a6bc9d227741afcc95d',
    messagingSenderId: '628420378856',
    projectId: 'food-go-17a5d',
    authDomain: 'food-go-17a5d.firebaseapp.com',
    storageBucket: 'food-go-17a5d.firebasestorage.app',
    measurementId: 'G-DNDSE3NGBP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCr9eK2rGlAGrKwWLYSIvdmrzWJp74ebQo',
    appId: '1:628420378856:android:53ef385ebabaccfcfcc95d',
    messagingSenderId: '628420378856',
    projectId: 'food-go-17a5d',
    storageBucket: 'food-go-17a5d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8IeOnh7Rj8XWSXR7ZZMSu-OHZ0XktoU0',
    appId: '1:628420378856:ios:6e1b1582a38c2712fcc95d',
    messagingSenderId: '628420378856',
    projectId: 'food-go-17a5d',
    storageBucket: 'food-go-17a5d.firebasestorage.app',
    iosBundleId: 'com.example.feFoodgoCustomers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8IeOnh7Rj8XWSXR7ZZMSu-OHZ0XktoU0',
    appId: '1:628420378856:ios:6e1b1582a38c2712fcc95d',
    messagingSenderId: '628420378856',
    projectId: 'food-go-17a5d',
    storageBucket: 'food-go-17a5d.firebasestorage.app',
    iosBundleId: 'com.example.feFoodgoCustomers',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbPguKOd1ahIWG-KoxusLqJ1hTJKGsxOc',
    appId: '1:628420378856:web:d48262ee56d2cec3fcc95d',
    messagingSenderId: '628420378856',
    projectId: 'food-go-17a5d',
    authDomain: 'food-go-17a5d.firebaseapp.com',
    storageBucket: 'food-go-17a5d.firebasestorage.app',
    measurementId: 'G-9PXP0ERXQS',
  );
}
